# lumen_ui_config.yaml (place in project root)
templates:
  button:
    path: "lib/src/widgets/buttons/button_template.dart"
    folder: "buttons"
  inputfield:
    path: "lib/src/widgets/inputfields/basic_inputfield.dart"
    folder: "inputfields"
  # Add more templates as needed