# lumen_ui_config.yaml
templates:
  button:
    primarybutton:
      path: "lib/src/widgets/buttons/primary_button/template.dart"
      folder: "buttons/primary_button"
      suffix_file: "_button"
      suffix_name: "Button"
  inputfield:
    primarytextinputfield:
      path: "lib/src/widgets/inputfields/primary_text_inputfield/template.dart"
      folder: "inputfields/primary_text_inputfield"
      suffix_file: "_textinputfield"
      suffix_name: "TextInputfield"
