# flutter_ui_generator_config.yaml
generator:
  # Allowed component types
  component_types:
    - button
    - textfield
    - card
    - dialog

  # Default generation options
  defaults:
    output_directory: lib/ui
    file_naming: snake_case # or camelCase, kebab-case

  # Optional custom templates
  custom_templates:
    button:
      - primary
      - secondary
      - outlined
    textfield:
      - standard
      - underlined
      - outlined